name: Add a comment
on:
  pull_request:
    branches: [ master ]
jobs:
  sample2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |          
        await github.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: "Hello! Sample comment was added!"
        });
